import csv

courses = [
"Applied Physics/Physics",
"Applied Mathematics/Mathematics",
"Applied Statistics/Statistics",
"Biochemistry",
"Biology",
"Botany",
"Chemistry",
"Environmental Science",
"Geology",
"Human Biology",
"Marine Biology",
"Marine Science",
"Meteorology",
"Molecular Biology and Biotechnology",
"Computer Science",
"Cyber Security",
"Entertainment and Multimedia Computing/Game Development and Animation",
"Information System",
"Information Technology",
"Library and Information Science",
"Agriculture and Biosystems Engineering",
"Ceramic Engineering",
"Chemical Engineering",
"Civil Engineering",
"Computer Engineering",
"Electrical Engineering",
"Electronics Engineering/Electronics and Communications Engineering",
"Food Engineering",
"Geodetic Engineering",
"Industrial Engineering",
"Manufacturing/Production Engineering",
"Materials Engineering",
"Mechanical Engineering",
"Mechatronics Engineering",
"Metallurgical Engineering",
"Mining Engineering",
"Petroleum Engineering",
"Robotics Engineering",
"Sanitary Engineering",
"Structural Engineering",
"Aircraft Maintenance Technology",
"Aviation Related Programs",
"Engineering Technology",
"Industrial Technology",
"Mechatronics Engineering Technology",
"Architecture",
"Fine Arts",
"Interior Design",
"Landscape Architecture",
"Environmental Planning",
"Accountancy",
"Business Analytics (straight or major)",
"Hospitality Management/Hotel and Restaurant Management",
"Tourism Management/Tourism",
"Doctor of Dental Medicine",
"Doctor of Optometry",
"Medical Technology/Medical Laboratory Science",
"Midwifery",
"Nursing",
"Nutrition and Dietetics",
"Occupational Therapy",
"Pharmacy",
"Physical Therapy",
"Radiologic Technology",
"Respiratory Therapy",
"Speech Language Pathology",
"Marine Engineering",
"Marine Transportation",
"Community Development",
"Human Services (Guidance and Counselling)",
"Indigenous Peoples Studies/Education",
"Peace Studies/Education",
"Psychology",
"Social Work",
"Secondary Education major in Science and Mathematics",
"Culture and Arts",
"Early Childhood Education",
"Special Needs Education",
"Sports and Exercise Science",
"Agribusiness",
"Agro-Forestry",
"Data Science and Analytics",
"Disaster Risk Management/Climate Change",
"Renewable/Sustainable Energy",
"Communication and Media Studies",
"Broadcast Communication",
"Communication Arts",
"Communication Research",
"Development Communication",
"Journalism",
"Humanities and Arts",
"Creative Writing",
"English Language Studies",
"Filipino Language and Literature",
"History",
"Music Education",
"Philosophy",
"Theology",
"Law and Legal Education",
"Juris Doctor/Law",
"Veterinary Medicine",
"Physical Sciences",
"Chemical Science",
"Fisheries and Aquatic Studies",
"Fisheries",
"Sports Science",
"Forestry and Environmental Studies",
"Forestry",
"Public Health",
"Tourism and Hospitality Education",
"Tourism",
"Political Science and Public Administration",
"Political Science",
"Public Administration",
"Industrial Design",
"Fashion Design and Merchandising",
"Military Education",
"Agriculture",
"Architecture and Allied Programs",
"Architectural Engineering",
"Arts and Design",
"Advertising Arts",
"Animation",
"Fashion Design",
"Film",
"Graphic Design",
"Painting",
"Photography",
"Behavioral Sciences",
"Anthropology",
"Sociology",
"Religious Studies",
"Development Studies",
"Library Science and Information Studies",
"Linguistics",
"Mathematics and Statistics",
"Mathematics",
"Statistics",
"Philosophy and Ethics",
"Ethics",
"Physical Education",
"Science Education",
"Technology Education",
"Theological Education",
"Urban and Regional Planning"
]

cities = [
"Bangued",
"Cabadbaran",
"Butuan",
"Bayugan",
"San Francisco",
"Kalibo",
"Legazpi",
"Ligao",
"Tabaco",
"San Jose de Buenavista",
"Kabugao",
"Baler",
"Isabela City",
"Balanga",
"Basco",
"Batangas City",
"Lipa",
"Tanauan",
"Baguio",
"Naval",
"Tagbilaran",
"Malaybalay",
"Valencia",
"Malolos",
"Meycauayan",
"San Jose del Monte",
"Tuguegarao",
"Daet",
"Iriga",
"Naga",
"Mambajao",
"Roxas",
"Virac",
"Cavite City",
"Tagaytay",
"Trece Martires",
"Bogo",
"Carcar",
"Cebu City",
"Danao",
"Lapu-Lapu",
"Mandaue",
"Naga",
"Nabunturan",
"Kidapawan",
"Tagum",
"Davao City",
"Panabo",
"Mati",
"San Jose",
"Borongan",
"Jordan",
"Lagawe",
"Batac",
"Laoag",
"Vigan",
"Iloilo City",
"Ilagan",
"Santiago",
"San Fernando",
"Biñan",
"Calamba",
"San Pablo",
"Santa Rosa",
"Iligan",
"Marawi",
"Baybay",
"Ormoc",
"Tacloban",
"Cotabato City",
"Boac",
"Masbate City",
"Oroquieta",
"Cagayan de Oro",
"Gingoog",
"Bontoc",
"Bacolod",
"Bago",
"Cadiz",
"Escalante",
"Himamaylan",
"Kabankalan",
"La Carlota",
"Sagay",
"San Carlos",
"Silay",
"Sipalay",
"Talisay",
"Victorias",
"Bais",
"Bayawan",
"Canlaon",
"Dumaguete",
"Catarman",
"Cabanatuan",
"Gapan",
"San Jose",
"Bayombong",
"Mamburao",
"Calapan",
"Puerto Princesa",
"Angeles",
"San Fernando",
"Alaminos",
"Dagupan",
"San Carlos",
"Urdaneta",
"Lucena",
"Cabarroguis",
"Antipolo",
"Cainta",
"Rodriguez",
"Odiongan",
"Calbayog",
"Siquijor",
"Sorsogon City",
"Koronadal",
"Maasin",
"Isulan",
"Surigao City",
"Tandag",
"Tarlac City",
"Bongao",
"Iba",
"Dapitan",
"Dipolog",
"Pagadian",
"Ipil"
]

output = []

with open('best_colleges.csv', mode='w', newline='', encoding='utf-8') as csvfile:
    csv_writer = csv.writer(csvfile, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)

    # Write the header row
    header_row = [city for city in cities]
    csv_writer.writerow(header_row)

    # Write the rows for each course
    for course in courses:
        row = [f"Best College for {course} in {city}" for city in cities]
        csv_writer.writerow(row)
